# Generated by Django 4.0.2 on 2024-02-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='evento_cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
